blog_project/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('blogger/<int:pk>', views.BloggerDetailView.as_view(), name='blogger-detail'),
]

urlpatterns += [
    path('blog/<int:pk>/create', views.CreateComment.as_view(), name='create-comment'),
]

urlpatterns += [
    path('signup/', views.user_signup, name='signup'),
]

blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application
urlpatterns += [
    path('blog/', include('blog.urls')),
]

# Add URL maps to redirect the base URL to our application
urlpatterns += [
    path('', RedirectView.as_view(url='blog/', permanent=True)),
]

# Use static() to add URL mapping to serve static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

blog_project/blog/models.py
from django.db import models
import uuid

from django.urls import reverse # Used in get_absolute_url() to get URL for specified ID

from django.db.models import UniqueConstraint # Constrains fields to unique values
from django.db.models.functions import Lower # Returns lower cased value of field
from django.contrib.auth.models import User

# Create your models here.

class Type(models.Model):
    """Model representing a blog type."""
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter a blog type (e.g. News, food, travel etc.)"
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a particular genre instance."""
        return reverse('type-detail', args=[str(self.id)])

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='type_name_case_insensitive_unique',
                violation_error_message = "Type already exists (case insensitive match)"
            ),
        ]

class Blog(models.Model):
    """Model representing a blog."""
    title = models.CharField(max_length=200)
    post_date = models.DateField(auto_now_add=True)
    blogger = models.ForeignKey('Blogger', on_delete=models.RESTRICT, null=True)

    content = models.TextField(
        max_length=2000, help_text="Enter the content of the blog")

    type = models.ForeignKey(Type, on_delete=models.RESTRICT, null=True)

    class Meta:
        ordering = ['post_date']

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this blog."""
        return reverse('blog-detail', args=[str(self.id)])

class Blogger(models.Model):
    """Model representing an blogger."""
    name = models.CharField(max_length=100)
    bio = models.TextField(
        max_length=1000, help_text="Enter the bio of the blogger", default='')

    def get_absolute_url(self):
        """Returns the URL to access a particular blogger instance."""
        return reverse('blogger-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.name}'

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date_time = models.DateTimeField(auto_now_add=True)
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.",default="")

    class Meta():
        ordering = ['date_time']

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title=75
        if len(self.description)>len_title:
            titlestring=self.description[:len_title] + '...'
        else:
            titlestring=self.description
        return titlestring

blog_project/blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ['username', 'password1', 'password2']

blog_project/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

from .models import Blog, Blogger, Type, Comment
from .forms import SignupForm

# Create your views here.
def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_blogs = Blog.objects.all().count()

    # The 'all()' is implied by default.
    num_bloggers = Blogger.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_blogs': num_blogs,
        'num_bloggers': num_bloggers,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class BlogListView(generic.ListView):
    model = Blog
    context_object_name = 'blog_list'
    paginate_by = 5

class BlogDetailView(generic.DetailView):
    model = Blog

class BloggerListView(generic.ListView):
    model = Blogger
    context_object_name = 'blogger_list'
    paginate_by = 5

class BloggerDetailView(generic.DetailView):
    model = Blogger

class CreateComment(LoginRequiredMixin, generic.CreateView):
    model = Comment
    fields = ['description',]

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(CreateComment, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['blog'] = get_object_or_404(Blog, pk = self.kwargs['pk'])
        return context
        
    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of comment
        form.instance.author = self.request.user
        #Associate comment with blog based on passed id
        form.instance.blog=get_object_or_404(Blog, pk = self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(CreateComment, self).form_valid(form)

    def get_success_url(self): 
        """
        After posting comment return to associated blog.
        """
        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'],})
    
# signup page
def user_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})

blog_project/blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Our Home Blog</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'blogs' %}">All Blogs</a></li>
              <li><a href="{% url 'bloggers' %}">All Bloggers</a></li>
            </ul>

            <ul class="sidebar-nav">
              {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>

                <li>
                  <form id="logout-form" method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link">Logout</button>
                  </form>
                </li>
              {% else %}
                <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
              {% endif %}
          {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}
            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                            <span class="page-current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

blog_project/blog/templates/blog/blog_detail.html
{% extends "base_generic.html" %}
{% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

{% block content %}
  <h1>Title: {{ blog.title }}</h1>

  <p><strong>Post Date:</strong> {{ blog.post_date }}</p>
  <p><strong>Blogger:</strong> <a href="{{ blog.blogger.get_absolute_url }}">{{ blog.blogger }}</a></p>
  <p><strong>Description:</strong><br>&emsp;&emsp;{{ blog.content }}</p>
  <p><strong>Comments</strong></p>
  <p>There are {{ blog.comment_set.all|length }} comments.</p>
  {% if user.is_authenticated %}
    <a href="{% url 'create-comment' blog.id %}">Add a new comment</a></p>
  {% else %}
    <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
  {% endif %} 
  {% for comment in blog.comment_set.all %}
  <hr>
  <p>{{comment.author}} ({{comment.date_time}}) - {{comment.description}}</p>
  {% endfor %}
  <hr>
{% endblock %}

blog_project/blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}
{% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

{% block content %}
  <h1>Blog List</h1>
  {% if blog_list %}
    <ul>
      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>
        ({{blog.post_date}}) - <a href="{{ blog.blogger.get_absolute_url }}">{{ blog.blogger }}</a>
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no blogs yet in this site.</p>
  {% endif %}
{% endblock %}

blog_project/blog/templates/blog/blogger_detail.html
{% extends "base_generic.html" %}
{% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

{% block content %}
  <h1>Blogger: {{ blogger.name }}</h1>

  <p><strong>Bio:</strong><br>{{ blogger.bio }}</p>
  <p><strong>Blogs List:</strong></p>
  <ul>
    {% for blog in blogger.blog_set.all %}
      <li><a href="{% url 'blog-detail' blog.pk %}">{{blog}}</a> - ({{ blog.post_date }})</li>
      {% empty %}
      <p>This blogger hasn't post any blogs.</p>
    {% endfor %}
  </ul>
{% endblock %}

blog_project/blog/templates/blog/blogger_list.html
{% extends "base_generic.html" %}
{% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

{% block content %}
  <h1>All Bloggers</h1>
  {% if blogger_list %}
    <ul>
      {% for blogger in blogger_list %}
      <li>
        <a href="{{ blogger.get_absolute_url }}">{{ blogger.name }}</a>
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no bloggers yet in this site.</p>
  {% endif %}
{% endblock %}

blog_project/blog/templates/blog/comment_form.html
{% extends "base_generic.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'blog-detail' blog.pk %}">{{blog.title}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

blog_project/blog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Our Home Blog</h1>
  <p>
    Welcome to Our Home Blog, a website developed by
    <em>Mozilla Developer Network</em>!
  </p>
  <h2>Dynamic content</h2>
  <p>The blog has the following record counts:</p>
  <ul>
    <li><strong>Blog:</strong> {{ num_blogs }}</li>
    <li><strong>Bloggers:</strong> {{ num_bloggers }}</li>
  </ul>

  <p>
    You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>
{% endblock %}

blog_project/blog/templates/signup.html
<h1>Signup</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Signup</button>
    <a href="{% url 'login' %}">Already have account?</a>
</form>